server:
  port: 9092
okta:
  oauth2:
    issuer: https://your-okta-domain/oauth2/default
    client-id: CLIENT_ID
    client-secret: CLIENT_SECRET
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9092/oauth2/token
            scope:
              - openid
              - offline_access
        provider:
          okta:
            token-uri: https://your-okta-domain/oauth2/default/v1/token
            authorization-uri: https://your-okta-domain/oauth2/default/v1/authorize
